[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Enable CORS headers
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.daily.co https://*.firebaseapp.com https://*.googleapis.com https://*.sentry.io https://assets.calendly.com https://*.youtube.com https://*.ytimg.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      img-src 'self' data: https://*.daily.co https://*.firebaseapp.com https://*.googleapis.com https://*.wikimedia.org https://*.licdn.com https://*.shutterstock.com https://*.vapi.ai https://*.gifer.com https://*.giphy.com https://*.ytimg.com;
      font-src 'self' https://fonts.gstatic.com;
      connect-src 'self' https://*.daily.co https://*.firebaseapp.com https://*.googleapis.com https://*.sentry.io https://*.vapi.ai https://api.vapi.ai wss://*.daily.co https://topedge-backend.netlify.app https://*.calendly.com https://calendly.com;
      frame-src 'self' https://*.daily.co https://*.firebaseapp.com https://*.youtube.com https://*.calendly.com https://calendly.com;
      media-src 'self' https://*.daily.co blob: https://*.ytimg.com;
    """

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true
  optimize = true

[context.production.environment]
  NODE_ENV = "production"
  VITE_API_URL = "https://topedge-backend.netlify.app" 