[build]
  command = "npm run build:netlify"
  publish = "dist"

[[redirects]]
  from = "/community/*"
  to = "/community.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200