import { Helmet } from 'react-helmet-async';
import {
  Shield,
  FileText,
  Mail,
  Scale,
  Ban,
  Server,
  ShoppingBag,
  AlertTriangle,
  Clock,
  Wallet,
  Megaphone,
  Lock,
  Gavel,
  RefreshCw,
  Building2,
} from 'lucide-react';
import LegalEntityContactCard from '../components/legal/LegalEntityContactCard';
import LegalPageShell from '../components/legal/LegalPageShell';
import {
  COMPANY_BRAND_NAME,
  COMPANY_LEGAL_NAME,
  COMPANY_EMAIL,
  LEGAL_LAST_UPDATED_LABEL,
  COMPANY_GOVERNING_LAW,
  COMPANY_VENUE,
  COMPANY_GSTIN,
  COMPANY_ADDRESS_ONE_LINE,
  COMPANY_SITE_TERMS_URL,
  LEGAL_DOCS_VERSION,
} from '../legal/companyIdentity';
import '../styles/legal-page.css';

/**
 * Merchant Terms of Service — enterprise SaaS form for Indian D2C + WhatsApp/Shopify.
 * Not legal advice. Material changes bump LEGAL_DOCS_VERSION (FE + BE must match).
 */
export default function TermsPage() {
  const sections = [
    {
      id: 'electronic-record',
      icon: FileText,
      title: '1. Electronic record & acceptance',
      content: (
        <>
          <p>
            This document is an electronic record under the Information Technology Act, 2000 and rules thereunder.
            It is generated by a computer system and does not require a physical or digital signature.
          </p>
          <p>
            These Terms of Service (&quot;Terms&quot;) govern access to and use of {COMPANY_BRAND_NAME}, operated by{' '}
            <strong>{COMPANY_LEGAL_NAME}</strong> (&quot;TopEdge,&quot; &quot;Company,&quot; &quot;we,&quot; &quot;us&quot;), including the dashboard at{' '}
            <strong>https://dash.topedgeai.com</strong>, APIs at <strong>https://api.topedgeai.com</strong>, workers,
            webhooks, storefront scripts, Shopify app extensions, and related services (collectively, the &quot;Service&quot; / &quot;Platform&quot;).
          </p>
          <p>
            By creating an account, clicking accept, signing in, connecting Shopify/Meta/WhatsApp or other integrations,
            starting a trial, paying a fee, or otherwise using the Service, you give free, specific, informed, and
            unconditional consent to these Terms and our <a href="/privacy">Privacy Policy</a>, forming a binding contract.
            If you do not agree, do not use the Service.
          </p>
          <p>
            If you act for a company, partnership, LLP, or other entity, you represent that you have authority to bind that entity.
            &quot;You&quot; / &quot;Merchant&quot; means that entity and its authorised users.
          </p>
        </>
      ),
    },
    {
      id: 'eligibility',
      icon: Scale,
      title: '2. Eligibility',
      content: (
        <>
          <p>
            The Service is available only to persons who can enter into legally binding contracts under the Indian Contract Act, 1872.
            Minors (under 18), undischarged insolvents, and persons of unsound mind are not eligible, except where a legal guardian
            contracts on their behalf as permitted by law.
          </p>
          <p>
            The Service is intended for business use (B2B) by merchants and agencies operating ecommerce or messaging programmes.
            Consumer statutory rights that cannot be waived by contract remain unaffected where they mandatorily apply.
          </p>
        </>
      ),
    },
    {
      id: 'definitions',
      icon: Building2,
      title: '3. Key definitions',
      content: (
        <>
          <ul>
            <li><strong>Merchant End User / End Customer:</strong> your shoppers, leads, or WhatsApp contacts.</li>
            <li><strong>Merchant Data:</strong> your account, configuration, templates, flows, and business content.</li>
            <li><strong>End-Customer Personal Data:</strong> personal data of Merchant End Users processed via the Service.</li>
            <li><strong>Subscription Fee:</strong> recurring or one-time platform fees for plans (Launch / Growth / Scale, DFY, etc.).</li>
            <li><strong>Channel / Usage Fees:</strong> amounts charged by Meta, WhatsApp, carriers, email providers, Shopify, Razorpay, or other third parties for messages, conversations, ads, or payments — often billed separately from Subscription Fees.</li>
            <li><strong>Trial:</strong> time-limited, unpaid or promotional access we may grant before a paid plan.</li>
            <li><strong>Documentation:</strong> in-product help, runbooks, and published product docs.</li>
          </ul>
        </>
      ),
    },
    {
      id: 'service-description',
      icon: Server,
      title: '4. The Service',
      content: (
        <>
          <p>
            TopEdge provides tools for conversational commerce and marketing for ecommerce brands, which may include
            WhatsApp Cloud API messaging, templates, journeys/flows, live inbox, campaigns, cart recovery assistance,
            order notifications, analytics, opt-in widgets, pixel/insights, and Shopify integrations.
          </p>
          <p>
            Features may be added, changed, limited by plan, feature-flagged, or discontinued. We will use reasonable efforts
            to give notice of material removals where practicable. Beta or &quot;Soon&quot; features may be incomplete and are
            provided AS IS without SLA.
          </p>
          <p>
            You are solely responsible for accurate configuration (credentials, templates, Meta approval, Shopify scopes,
            consent capture, flows, and staff access) and for all activity under your workspace.
          </p>
        </>
      ),
    },
    {
      id: 'accounts',
      icon: Lock,
      title: '5. Accounts &amp; authorised users',
      content: (
        <>
          <p>
            Registration is required. Keep login credentials confidential. You are responsible for all actions under your
            workspace, including team members and admin impersonation sessions you authorise.
          </p>
          <p>
            Provide true, accurate, and current registration and billing information (including GSTIN / state where required for invoices).
            We may suspend or refuse access if information is false or incomplete.
          </p>
          <p>
            Notify us promptly of suspected unauthorised access. We are not liable for loss arising from your failure to
            safeguard credentials or from sharing access with third parties.
          </p>
        </>
      ),
    },
    {
      id: 'trials-billing',
      icon: Clock,
      title: '6. Trials, fees, GST, no refunds',
      content: (
        <>
          <div className="legal-page__notice legal-page__notice--warn">
            <strong>Free trial ends = access locks.</strong> When a trial expires without a valid paid plan, unpaid
            grace period, or VIP/admin grant, the workspace may be locked or features disabled. Automations, campaigns,
            and messaging that require a live subscription will not continue to run. Extending trial or unlocking is at
            our discretion or via payment of applicable fees.
          </div>
          <p>
            We may offer a free or promotional trial. Trial length, scope, and limits are shown at signup or in the dashboard
            and may change for new trials. Trials are provided AS IS with no warranty of results.
          </p>
          <p>
            <strong>Subscription Fees</strong> for TopEdge platform plans on dash.topedgeai.com are billed via Razorpay,
            offline confirmation, Shopify Billing (where that channel applies), or other methods we designate.
            Prices are typically listed exclusive or inclusive of GST as shown at checkout; GST invoices follow Indian tax rules
            when tax identity (state / GSTIN) is provided.
          </p>
          <p>
            <strong>No refunds.</strong> Except where mandatory law requires otherwise, all Subscription Fees, setup fees,
            DFY fees, and prepaid credits are <strong>non-refundable</strong> once charged, confirmed, or deducted —
            including mid-cycle cancellation, unused message quota, partial months, change of mind, failure to configure
            Meta/Shopify, template rejection by Meta, or dissatisfaction with marketing results. Chargebacks initiated in
            bad faith may result in suspension and recovery of costs.
          </p>
          <p>
            Non-payment, failed Razorpay mandates, offline overdue after grace, or insufficient prepaid balance may result
            in suspension or lock of the Service until amounts due are cleared. You remain liable for fees incurred before lock.
          </p>
          <p>
            Discounts and credits are discretionary, one-time unless we state otherwise in writing, and do not create ongoing entitlements.
          </p>
        </>
      ),
    },
    {
      id: 'shopify-billing',
      icon: ShoppingBag,
      title: '7. Shopify App Store &amp; billing channels',
      content: (
        <>
          <p>
            The Shopify app connector may be <strong>free to install</strong> on the Shopify App Store. Shopify App Store
            listing terms and Shopify&apos;s billing rules apply to charges processed by Shopify. Optional TopEdge platform
            fees on dash.topedgeai.com may be separate and are not always required solely to keep the Shopify connector installed.
          </p>
          <p>
            Where your workspace is on a Shopify Billing channel, manage or cancel Shopify charges in Shopify Admin.
            Uninstalling the app does not automatically refund prior charges. Shopify compliance webhooks (including
            shop/redact) are described in our Privacy Policy.
          </p>
          <p>
            You must have rights to connect each store and to share store data under Shopify&apos;s terms and applicable law.
          </p>
        </>
      ),
    },
    {
      id: 'channel-fees',
      icon: Wallet,
      title: '8. Meta, WhatsApp &amp; third-party channel fees',
      content: (
        <>
          <p>
            Meta WhatsApp Business Platform, SMS, email, voice, ads, and similar channels charge their own fees
            (conversation/message categories, marketing rates, etc.). Those <strong>Channel / Usage Fees</strong> are set
            by third parties, may change without our control, and are generally <strong>in addition to</strong> TopEdge Subscription Fees.
          </p>
          <p>
            You are responsible for Meta Business Manager, WABA, payment methods on Meta, template approvals, quality rating,
            and compliance with Meta WhatsApp Business Policy. We do not control Meta delivery, template review outcomes,
            or Meta billing disputes.
          </p>
          <p>
            If we pass through or display estimated Channel Fees, estimates can be wrong; the third party&apos;s invoice controls.
            Continued use after we notify a pass-through rate change constitutes acceptance of the revised pass-through where permitted by law.
          </p>
        </>
      ),
    },
    {
      id: 'no-revenue-guarantee',
      icon: Megaphone,
      title: '9. No revenue, ROI, or results guarantee',
      content: (
        <>
          <div className="legal-page__notice legal-page__notice--warn">
            <strong>Read carefully.</strong> TopEdge provides software and related services. We do{' '}
            <strong>not</strong> guarantee sales, revenue, ROI, conversion rates, cart recovery rates, open rates,
            delivery rates, read rates, attribution accuracy, or any business outcome. Marketing copy, case studies,
            dashboards, sample/preview data, and DFY recommendations are illustrative only — not promises.
          </div>
          <p>
            Message delivery depends on Meta, carriers, user devices, privacy settings (e.g. read receipts), template status,
            opt-outs, network conditions, and your configuration. We do not warrant that any message will be delivered,
            read, or acted upon at any time, or at all.
          </p>
          <p>
            Analytics, attribution, and &quot;recovered revenue&quot; figures are estimates based on available signals and may be
            incomplete or incorrect. Do not rely on them as audited financial statements.
          </p>
          <p>
            AI-generated content, suggested flows, and automated replies may be inaccurate or inappropriate. You must review
            and approve customer-facing content and remain responsible for it.
          </p>
        </>
      ),
    },
    {
      id: 'shopify-data',
      icon: ShoppingBag,
      title: '10. Shopify &amp; Merchant / End-Customer data roles',
      content: (
        <>
          <p>
            Connecting Shopify authorises us to access and process store data needed for features you enable
            (orders, products, checkouts, customers, fulfilments, themes/embeds as scoped).
          </p>
          <p>
            For End-Customer Personal Data processed only to provide the Service to you, you are generally the{' '}
            <strong>Data Fiduciary / controller</strong> and we act as a <strong>Data Processor / service provider</strong>
            under applicable Indian law (including the Digital Personal Data Protection Act, 2023 as implemented) and other
            laws that apply to your customers. You must have a lawful basis, notices, and consents for messaging and tracking.
          </p>
          <p>See the <a href="/privacy">Privacy Policy</a> for collection, retention, Meta Platform Data, and deletion.</p>
        </>
      ),
    },
    {
      id: 'messaging-compliance',
      icon: Shield,
      title: '11. WhatsApp, messaging &amp; consent',
      content: (
        <>
          <p>
            You must obtain and document valid consent before marketing messages, and comply with Meta WhatsApp Business Policy,
            applicable Indian telecom/privacy rules (including TRAI where applicable), and foreign laws for international recipients.
          </p>
          <ul>
            <li>Honour opt-outs (e.g. <strong>STOP</strong> or configured keywords) — marketing and cart-recovery stops for that contact.</li>
            <li>Utility / service messages may still send where policy and law allow.</li>
            <li>Do not use the Service for unlawful spam, phishing, or deceptive practices.</li>
            <li>You are solely liable for content you send and for complaints, blocks, or Meta enforcement against your WABA.</li>
          </ul>
        </>
      ),
    },
    {
      id: 'acceptable-use',
      icon: Ban,
      title: '12. Acceptable use',
      content: (
        <>
          <p>You agree not to:</p>
          <ul>
            <li>Use the Service unlawfully or to violate Meta, Shopify, payment, or privacy rules.</li>
            <li>Probe, disrupt, overload, or bypass security, rate limits, or tenant isolation.</li>
            <li>Reverse engineer, resell, or create a competing service from the Platform except as permitted by law.</li>
            <li>Upload malware or infringing, defamatory, or illegal content.</li>
            <li>Misrepresent affiliation with TopEdge or use our marks without permission (except factual statements).</li>
          </ul>
          <p>We may suspend or terminate for violations, abuse, non-payment, or risk to the platform or others.</p>
        </>
      ),
    },
    {
      id: 'ip',
      icon: FileText,
      title: '13. Intellectual property',
      content: (
        <>
          <p>
            The Platform, software, designs, documentation, and TopEdge brands are owned by us or our licensors.
            We grant you a limited, revocable, non-exclusive, non-transferable licence to use the Service for your internal
            business during a valid subscription or trial, subject to these Terms.
          </p>
          <p>
            You retain ownership of Merchant Data and End-Customer Personal Data you provide. You grant us a licence to host,
            process, transmit, and display that data solely to provide and improve the Service, comply with law, and as in the Privacy Policy.
          </p>
          <p>
            You grant us a royalty-free right to use your name and logo to identify you as a customer (website, decks),
            unless you opt out in writing to {COMPANY_EMAIL}.
          </p>
        </>
      ),
    },
    {
      id: 'disclaimers',
      icon: AlertTriangle,
      title: '14. Disclaimers (AS IS)',
      content: (
        <>
          <div className="legal-page__notice legal-page__notice--warn">
            <strong>AS IS / AS AVAILABLE.</strong> TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SERVICE IS PROVIDED WITHOUT
            WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
            TITLE, NON-INFRINGEMENT, ACCURACY, QUIET ENJOYMENT, OR UNINTERRUPTED OR ERROR-FREE OPERATION.
          </div>
          <p>
            The Service depends on hosting providers, Redis/Mongo, networks, Meta, Shopify, Razorpay, email, DNS, and AI vendors.
            Outages, delays, data loss, webhook failures, and third-party policy changes may occur outside our control.
          </p>
          <p>
            Scheduled maintenance, security patches, and emergency interventions may cause temporary unavailability without liability.
          </p>
        </>
      ),
    },
    {
      id: 'liability-cap',
      icon: Shield,
      title: '15. Limitation of liability',
      content: (
        <>
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE ARE NOT LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL,
            EXEMPLARY, OR PUNITIVE DAMAGES; LOST PROFITS, REVENUE, SALES, GOODWILL, DATA, OR BUSINESS OPPORTUNITY;
            OR COST OF SUBSTITUTE SERVICES — WHETHER BASED ON CONTRACT, TORT, OR OTHERWISE — ARISING FROM THE SERVICE OR THESE TERMS.
          </p>
          <p>
            OUR AGGREGATE LIABILITY FOR ALL CLAIMS RELATING TO THE SERVICE SHALL NOT EXCEED THE GREATER OF:
            (A) THE SUBSCRIPTION FEES YOU PAID TO TOPEDGE FOR THE SERVICE IN THE THREE (3) MONTHS IMMEDIATELY BEFORE THE CLAIM; OR
            (B) INR 8,000 (or equivalent) if you had no such payments.
          </p>
          <p>
            Channel / Usage Fees paid to Meta or other third parties are not &quot;paid to TopEdge&quot; for this cap.
            Some jurisdictions disallow certain limits; we limit liability to the fullest extent permitted.
          </p>
        </>
      ),
    },
    {
      id: 'indemnity',
      icon: Gavel,
      title: '16. Indemnity',
      content: (
        <p>
          You will defend, indemnify, and hold harmless {COMPANY_LEGAL_NAME}, its partners, officers, employees, and agents
          from claims, damages, losses, and expenses (including reasonable legal fees) arising from: (a) your use of the Service;
          (b) Merchant Data or End-Customer Personal Data; (c) your messaging content, campaigns, or consent failures;
          (d) your breach of these Terms or law; or (e) disputes with your customers, Meta, Shopify, or payment providers.
        </p>
      ),
    },
    {
      id: 'termination',
      icon: Ban,
      title: '17. Suspension, termination &amp; effect',
      content: (
        <>
          <p>
            You may stop using the Service and request workspace deletion via{' '}
            <strong>Settings → Workspace → Delete workspace</strong> or email{' '}
            <a href={`mailto:${COMPANY_EMAIL}`}>{COMPANY_EMAIL}</a>.
          </p>
          <p>
            We may suspend or terminate immediately for breach, non-payment, legal risk, abuse, security incidents,
            or inactivity. We may also suspend for Meta/Shopify enforcement against your connected assets.
          </p>
          <p>
            On termination or lock: licences end; access may stop immediately; amounts due remain payable;{' '}
            <strong>no refund</strong> of prepaid fees (Section 6). Survival: Sections 9, 13–16, 18–20, and Privacy obligations.
          </p>
          <p>
            Shopify uninstall and Meta deletion callbacks are described in the Privacy Policy
            (<strong>https://api.topedgeai.com/api/meta/data-deletion</strong>, Shopify compliance webhooks).
          </p>
        </>
      ),
    },
    {
      id: 'force-majeure',
      icon: RefreshCw,
      title: '18. Force majeure',
      content: (
        <p>
          We are not liable for delay or failure caused by events beyond reasonable control, including natural disasters,
          war, terrorism, labour disputes, utility failures, internet backbone outages, DDoS, epidemic, government action,
          or failure of Meta, Shopify, cloud hosts, or payment networks.
        </p>
      ),
    },
    {
      id: 'changes',
      icon: FileText,
      title: '19. Changes to these Terms',
      content: (
        <>
          <p>
            We may update these Terms. The &quot;Last updated&quot; date and document version ({LEGAL_DOCS_VERSION}) will change.
            Material changes may be notified by email or in-product. Continued use after the effective date constitutes acceptance.
            If you do not agree, stop using the Service and delete your workspace.
          </p>
          <p>
            Sign-up and certain auth flows require acceptance of the current document version. An outdated acceptance may
            require re-acceptance before continued access.
          </p>
        </>
      ),
    },
    {
      id: 'general',
      icon: Scale,
      title: '20. General',
      content: (
        <>
          <p>
            <strong>Governing law.</strong> These Terms are governed by {COMPANY_GOVERNING_LAW}, without regard to conflict-of-law rules.
            Exclusive venue: {COMPANY_VENUE}, subject to mandatory consumer protections where they apply.
          </p>
          <p>
            <strong>Entire agreement.</strong> These Terms and the Privacy Policy are the entire agreement regarding the Service
            and supersede prior proposals on the same subject, except written DFY/order forms that expressly prevail on conflicting points.
          </p>
          <p>
            <strong>Severability.</strong> If a provision is unenforceable, the remainder stays in effect.
            <strong> Waiver.</strong> Failure to enforce is not a waiver.
            <strong> Assignment.</strong> You may not assign without our consent; we may assign to an affiliate or successor.
          </p>
          <p>
            <strong>Notices.</strong> We may notify you via registered email, dashboard banner, or WhatsApp to your admin contacts.
            Legal notices to us: {COMPANY_EMAIL}, {COMPANY_ADDRESS_ONE_LINE}. GSTIN: {COMPANY_GSTIN}.
          </p>
          <p>
            <strong>Language.</strong> English controls. Translations are for convenience only.
          </p>
          <p>
            <strong>No legal advice.</strong> These Terms are a commercial contract, not advice. Consult your counsel for your situation.
          </p>
        </>
      ),
    },
    {
      id: 'contact',
      icon: Mail,
      title: '21. Contact',
      content: (
        <>
          <p>
            Questions about these Terms for <strong>{COMPANY_BRAND_NAME}</strong> ({COMPANY_LEGAL_NAME}):
          </p>
          <LegalEntityContactCard />
          <p style={{ marginTop: '0.65rem', fontSize: '0.75rem', color: '#94a3b8' }}>
            Prefer email: <a href={`mailto:${COMPANY_EMAIL}`}>{COMPANY_EMAIL}</a>.
            Document version: {LEGAL_DOCS_VERSION}.
          </p>
        </>
      ),
    },
  ];

  return (
    <>
      <Helmet>
        <title>Terms of Service | TopEdge AI</title>
        <meta
          name="description"
          content="TopEdge AI Terms of Service — binding agreement for the dashboard, Shopify, and Meta / WhatsApp integrations. No ROI guarantee; no refunds except where law requires."
        />
        <link rel="canonical" href={COMPANY_SITE_TERMS_URL} />
        <meta property="og:type" content="website" />
        <meta property="og:url" content={COMPANY_SITE_TERMS_URL} />
        <meta property="og:title" content="Terms of Service | TopEdge AI" />
        <meta
          property="og:description"
          content="Terms of Service for TopEdge AI (TopEdge Ai). Governing law India · Ahmedabad venue."
        />
        <meta name="robots" content="index, follow" />
      </Helmet>
      <LegalPageShell
        documentTitle="Terms of Service | TopEdge AI"
        pageTitle="Terms of Service"
        lastUpdated={LEGAL_LAST_UPDATED_LABEL}
        siblingHref="/privacy"
        siblingLabel="Privacy"
        intro={(
          <>
            Binding agreement between you and <strong>{COMPANY_LEGAL_NAME}</strong> (brand {COMPANY_BRAND_NAME}),
            a partnership with principal place of business in Ahmedabad, Gujarat, India.
            If you do not agree, do not use the Service.
          </>
        )}
        introNote={(
          <>
            Key commercial points: <strong>no revenue/ROI guarantee</strong>; <strong>no refunds</strong> (except where law mandates);
            <strong> trial expiry may lock the workspace</strong>; Meta/WhatsApp channel fees are separate; Service is AS IS.
            Full detail in the sections below.
          </>
        )}
        sections={sections}
        acknowledgment={(
          <>
            See also our <a href="/privacy">Privacy Policy</a>. By using the Service you acknowledge both documents.
          </>
        )}
      />
    </>
  );
}
