/**
 * Vendor the documentation content into the dashboard app.
 *
 * The canonical content lives here, next to the SEO pipeline that prerenders it,
 * generates its Markdown mirrors and gates it on snippet budgets. The dashboard
 * renders the same text for in-product help, so it gets a generated copy rather
 * than a second hand-maintained set that would drift within a week.
 *
 * Emitted as JSON, not TypeScript: the dashboard is a JavaScript project, and a
 * data file it can `import` directly keeps its toolchain out of the question.
 * `contentHash` lets the dashboard's own check fail its build when somebody edits
 * the vendored copy instead of the source.
 *
 * Usage: node scripts/sync-docs.mjs [path-to-dashboard-repo]
 *   default: ../chatbot-dashboard-frontend
 */
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadDocsRegistry } from './load-docs-content.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const target = path.resolve(
  process.argv[2] || path.join(root, '..', 'chatbot-dashboard-frontend'),
);
const outDir = path.join(target, 'src', 'pages', 'docs', 'vendor');

if (!fs.existsSync(path.join(target, 'package.json'))) {
  console.error(`✖ no package.json at ${target} — pass the dashboard repo path as an argument`);
  process.exit(1);
}

const { DOC_ARTICLES, DOC_NAV, docPathFor } = await loadDocsRegistry();

const payload = {
  groups: DOC_NAV.map((group) => ({
    id: group.id,
    label: group.label,
    blurb: group.blurb,
    slugs: group.articles.map((a) => a.slug),
  })),
  articles: DOC_ARTICLES.map((article) => ({
    slug: article.slug,
    path: docPathFor(article.slug),
    group: article.group,
    navLabel: article.navLabel,
    title: article.title,
    description: article.description,
    h1: article.h1,
    lead: article.lead,
    keywords: article.keywords,
    updated: article.updated,
    dashboard: article.dashboard ?? null,
    faqs: article.faqs ?? [],
    blocks: article.blocks,
  })),
};

// Hash the content only, so re-running the sync with no content change does not
// churn the file (and therefore does not produce a no-op commit).
const contentHash = crypto
  .createHash('sha256')
  .update(JSON.stringify(payload))
  .digest('hex');

const file = {
  $generated: 'scripts/sync-docs.mjs in topedge-frontend-site — DO NOT EDIT BY HAND',
  $canonical: 'https://topedgeai.com/docs',
  contentHash,
  ...payload,
};

fs.mkdirSync(outDir, { recursive: true });

const outFile = path.join(outDir, 'docs.json');
const existing = fs.existsSync(outFile) ? JSON.parse(fs.readFileSync(outFile, 'utf8')) : null;
if (existing?.contentHash === contentHash) {
  console.log(`✓ ${path.relative(target, outFile)} already current (${payload.articles.length} pages)`);
} else {
  fs.writeFileSync(outFile, `${JSON.stringify(file, null, 2)}\n`, 'utf8');
  console.log(`✅ Wrote ${path.relative(target, outFile)} (${payload.articles.length} pages)`);
}

fs.writeFileSync(
  path.join(outDir, 'README.md'),
  `# Vendored documentation content

\`docs.json\` is generated. **Do not edit it here.**

The source of truth is \`src/marketing/docs/content/\` in the
\`topedge-frontend-site\` repository, where the same content is prerendered as the
public documentation at <https://topedgeai.com/docs>, checked against SEO snippet
budgets, and mirrored as plaintext Markdown for AI crawlers.

## To change a doc page

1. Edit the content module in \`topedge-frontend-site\`.
2. Run \`npm run check:docs\` there.
3. Run \`node scripts/sync-docs.mjs ../chatbot-dashboard-frontend\`.
4. Commit both repositories.

## Why the build fails if you edit this file

\`npm run check:docs-vendor\` recomputes \`contentHash\` over the content and
compares it with the stored value. Editing \`docs.json\` directly breaks that
check — which is the point: a local edit here would silently diverge from the
public documentation, and the public copy is the one customers and search
engines read.
`,
  'utf8',
);

// The dashboard's own guard, shipped alongside the data so the two cannot be
// separated. Written by the sync so there is one definition of the hash rule.
fs.writeFileSync(
  path.join(target, 'scripts', 'checkDocsVendor.mjs'),
  `/**
 * AUTO-GENERATED by scripts/sync-docs.mjs in topedge-frontend-site.
 *
 * Fails when src/pages/docs/vendor/docs.json has been edited in this repository
 * instead of at its source. The public documentation at
 * https://topedgeai.com/docs is generated from the same content, so a local edit
 * here would put in-product help and the public pages out of step with no other
 * signal that it had happened.
 *
 * Usage: npm run check:docs-vendor
 */
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const file = path.resolve(__dirname, '..', 'src', 'pages', 'docs', 'vendor', 'docs.json');

if (!fs.existsSync(file)) {
  console.error('✖ src/pages/docs/vendor/docs.json is missing — run sync-docs.mjs in topedge-frontend-site');
  process.exit(1);
}

const data = JSON.parse(fs.readFileSync(file, 'utf8'));
const { contentHash, groups, articles } = data;
const actual = crypto
  .createHash('sha256')
  .update(JSON.stringify({ groups, articles }))
  .digest('hex');

if (actual !== contentHash) {
  console.error('');
  console.error('✖ vendored docs content has been edited in this repository.');
  console.error(\`   stored hash: \${contentHash}\`);
  console.error(\`   actual hash: \${actual}\`);
  console.error('');
  console.error('   Edit the content in topedge-frontend-site/src/marketing/docs/content/,');
  console.error('   then re-run: node scripts/sync-docs.mjs ../chatbot-dashboard-frontend');
  console.error('');
  process.exit(1);
}

console.log(\`✓ vendored docs content intact (\${articles.length} pages, hash \${contentHash.slice(0, 12)})\`);
`,
  'utf8',
);

console.log(`✅ Wrote ${path.relative(target, path.join(outDir, 'README.md'))}`);
console.log(`✅ Wrote ${path.relative(target, path.join(target, 'scripts', 'checkDocsVendor.mjs'))}`);
